language: elixir
sudo: false
elixir:
  - 1.6
otp_release:
  - 19.3
  - 20.0
env:
  - MIX_ENV=test
script:
  - mix ecto.create
  - mix ecto.migrate
  - mix test
  - mix coveralls.travis
services:
  - postgresql
addons:
  postgresql: "9.6"
