language: elixir
sudo: false
elixir:
  - 1.6
otp_release:
  - 19.3
  - 20.0
env:
  - MIX_ENV=test
services:
  - postgresql
script:
  - mix ecto.create
  - mix ecto.migrate
  - mix test
  - mix coveralls.travis
services:
  - postgresql
after_script:
  - MIX_ENV=dev mix deps.get
  - MIX_ENV=dev mix inch.report
addons:
  postgresql: "9.6"
