version: "2"
services:
  football:
    build:
      context: ../../
      dockerfile: ./automation/docker/elixir/Dockerfile
    command: mix do ecto.create, ecto.migrate, phx.server
    expose:
      - "4000"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
